### ISSUE TITLE
datacenter not found error

### ISSUE THREAD

**Issue by danhiris** [chef-partners/chef-provisioning-vsphere#23]
I'm trying to converge but I keep getting a datacenter not found error. The datacenter is in a folder. 
I have a datacenter on a lab cluster that isn't in a specific folder, and everything works great.

I tested this from knife and the datacenter is found. For some reason this is not able to find the datacenter if it's under a folder structure. 

I think this code doesn't take datacenters in folders under account.

```
rootFolder = vim.serviceInstance.content.rootFolder
        dc = rootFolder.childEntity.grep(RbVmomi::VIM::Datacenter).find
```

When looking up data centers, folders should be traversed, not just doing a find on the rootFolder.
This is how knife vsphere does it:

```
      def traverse_folders_for_dc(folder, dcname)
        children = folder.children.find_all
        children.each do |child|
          if child.class == RbVmomi::VIM::Datacenter && child.name == dcname
            return child
          elsif child.class == RbVmomi::VIM::Folder
            dc = traverse_folders_for_dc(child, dcname)
            return dc if dc
          end
        end

```

![screen shot 2017-05-08 at 4 09 41 pm](https://cloud.githubusercontent.com/assets/16544443/25829067/d920c0de-3408-11e7-87e1-a1414ae02422.png)

datacenter: 'USF Support Centers/1P - Phoenix NPC - QA'

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [vSphere Datacenter not found [USF Support Centers/1P - Phoenix NPC - QA]] on default-redhat
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by jjasghar** [comment]
resolved with 2.0.0 release.
