### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by michaeltlombardi** [chef-partners/chef-provisioning-vsphere#25]
This project doesn't have a changelog, but it should.

## Expected Behavior
Users and developers should be able to review a changelog for this project which adheres to the [keepachangelog format](http://keepachangelog.com/en/0.3.0/) and thus meets the following criteria:

> - It’s made for humans, not machines, so legibility is crucial.
> - Easy to link to any section (hence Markdown over plain text).
> - One sub-section per version.
> - List releases in reverse-chronological order (newest on top).
> - Write all dates in `YYYY-MM-DD` format. (Example: `2012-06-02` for `June 2nd, 2012`.) It’s international, [sensible](http://xkcd.com/1179/), and language-independent.
> - Explicitly mention whether the project follows [Semantic Versioning][https://semver.org].
> - Each version should:
>   - List its release date in the above format.
>   - Group changes to describe their impact on the project, as follows:
>     - `Added` for new features.
>     - `Changed` for changes in existing functionality.
>     - `Deprecated` for once-stable features removed in upcoming releases.
>     - `Removed` for deprecated features removed in this release.
>     - `Fixed` for any bug fixes.
>     - `Security` to invite users to upgrade in case of vulnerabilities.

## Current Behavior
The project has no changelog file.

## Possible Solution
Use the [keepachangelog format](http://keepachangelog.com/en/0.3.0/) and ensure that it is updated for each new version/release.

Maybe not useful to backport every version, but at least the `2.0.0` changes?

## Context
Keeping a standardized changelog makes it easy for people to see and understand what has happened version to version and when those versions were released.

**Comment by jjasghar** [comment]
But but we do?

https://github.com/chef-partners/chef-provisioning-vsphere/blob/master/CHANGELOG.md

**Comment by jjasghar** [comment]
I think this invalid. If you'd like to add more data to the Changelog, i'm all about it. I pulled default from: https://github.com/skywinder/github-changelog-generator and if you'd like to add more, please propose a change to the `Rakefile` so we can keep it automated.

**Comment by michaeltlombardi** [comment]
I looked twice and didn't see it... weird. Sorry about this!
