### ISSUE TITLE
kitchen destroy not destroying machines

### ISSUE THREAD

**Issue by akulbe** [chef-partners/chef-provisioning-vsphere#37]
### Versions:
* Version of Chef-Provisioning: 2.2.1
* Version of Chef-Provisioning-vSphere:  2.0.3
* Version of Chefdk: 1.4.3
* Version of Chef-client: 12.19.36
* Version of kitchen: 1.16.0

### Platform Details
* Version of vSphere/vCenter: 6.5.0
* Version of ESXi: 6.5.0

### Scenario:
kitchen destroy

### Steps to Reproduce:
Run 'kitchen destroy' and observe cloned VM still exists in VMware.

### Expected Result:
VM to be destroyed.

### Actual Result:
VM remains

**Comment by juanxhos** [comment]
this always happens if last state cam out with error

**Comment by jjasghar** [comment]
Maybe we should find a way to clean up ERROR'd machines? If this is expected, we should at least put this in the README so we have documented and higher visibility.

**Comment by jjasghar** [comment]
If anyone wants to put the PR in to fix the readme, i'd love to see it. :)
