### ISSUE TITLE
Failures during create phase of test-kitchen leave abandoned VMs

### ISSUE THREAD

**Issue by lomeroe** [chef-partners/chef-provisioning-vsphere#53]
### Versions:

* Version of Chef-Provisioning: 2.3.2
* Version of Chef-Provisioning-vSphere: 2.0.5

### Platform Details

* Version of vSphere/vCenter: 6.0
* Version of ESXi: 6.0

### Scenario:
Failures during the "create" phase of test-kitchen result in VMs that must be manually cleaned up (i.e. a subsequent test-kitchen run will not delete the VM created)

### Steps to Reproduce:
A failure must occur during the create phase.  As described in #52 this can happen if an IPv6 address is returned by VMWare tools.  I've also seen this happen when the ESX server is under a heavy load, like during backups.

### Expected Result:
The VM clone is either deleted or at least a yml config file is created so a subsequent test-kitchen run can delete it.

### Actual Result:
VM is left running/in inventory and must be manually deleted.

**Comment by lomeroe** [comment]
@josh-barker #83 seems to work perfectly for fixing this -- great work and thank you!

**Comment by josh-barker** [comment]
You're welcome @lomeroe! :-)
