### ISSUE TITLE
Skip bootstrap after provisioning

### ISSUE THREAD

**Issue by shanxops** [chef-partners/chef-provisioning-vsphere#6]
Hi,
Is it possible to skip bootstrapping the node after provisioning, and just use the IP of the node else where.
Having a requirement, that does not need the provisioned node to be part of chef
thanks

**Comment by jjasghar** [comment]
So, to provision a few machines with the `machine` resource, but _not_ install `chef-client` on the provisioned machines?

**Comment by shanxops** [comment]
Yes @jjasghar , exactly
Scenarios like, 
- Some machine, not to be maintained by chef
- Need to add some static routes in the machine before bootstrap

So, is it possible to provision a machine and get the IP of the machine to use it further differently, out of the regualr flow.

**Comment by jjasghar** [comment]
I put some thought into this, and no, i think this is out of scope (for the time being) of this gem.

The point of using `chef-provisiong` is to provision compute resources for _chef_. Skipping seems like something that this tool shouldn't be used to do.

Though, in your use case, PowerCLI can do something like the following if you needed:

```powershell
$Cluster = Get-Cluster -Name Cluster
For ($i=0; $i -le 5; $i++) {
  New-VM -Name vm$i -Template TEMPLATE -ResourcePool $Cluster
}
```

or even teraform:

```
# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = "admin@vsphere.local"
  password       = "ADMIN!"
  vsphere_server = "192.168.0.x"
  allow_unverified_ssl = true
}

# create a vm
resource "vsphere_virtual_machine" "web" {
  name   = "terraform-web"
  vcpu   = 2
  memory = 4096
  datacenter = "Datacenter"

  network_interface {
    label = "VM Network"
  }

  disk {
    template = "Linux/ubuntu16-template"
    type = "thin"
    bootable = "true"
  }
}
```

There's a chance I might come across this down the line, but it'll be unlikely in the near future.

**Comment by jjasghar** [comment]
@shanmugakarna interestingly after talking to @tyler-ball it's actually already built into `chef-provisioning`

If you do something like:

```ruby
machine 'testing-ready' do
  tag 'mydb_master'
  action :ready
end
```

Notice the `action :ready` will provision and make sure the machine is up and waiting for you.

**Comment by skarungan** [comment]
Thank you so much @jjasghar. Sorry for the late reply. 

Its really awesome, it works perfect.
