### ISSUE TITLE
No IP generated in Ubuntu 18

### ISSUE THREAD

**Issue by jimbodragon** [chef-partners/chef-provisioning-vsphere#91]
### Versions:

* Version of Chef-Provisioning: 2.7.1
* Version of Chef-Provisioning-vSphere: 2.3.1

### Platform Details

* Version of vSphere/vCenter: 6.5.0.13000 Build 8024368
* Version of ESXi:VMware ESXi, 6.5.0, 7388607

### Scenario:

I'm trying to build a new VM with ubuntu 18 but the network card does not load automatically and event if I connect it manually while the VM is booting up, the VM fixe ip does not update.

### Steps to Reproduce:

Create a template with Ubuntu 18 and generate a new VM with chef-provisioning-vsphere under :boostrap_options =>{ :customization_spec => { :ipsettings => ip: "192.168.0.2"}}

### Expected Result:

No IP generated as it uses now Netplan in Ubuntu 18 and that I specify the chef code

**Comment by hrmmmwhynot** [comment]
You need to make sure you installed the vmtools from vcenter and not the open source version of vmtools that comes with Ubuntu. I found the open source version of vmtools doesn't fully work so the network and vm guest os calls to apply settings into the OS never happens.

If the Ubuntu you installed already has vmtools you need to uninstall and install the one from your vcenter.

**Comment by wduncanfraser** [comment]
Looks like it is related to: https://kb.vmware.com/s/article/56409?lang=en_US

This isn't an issue with this provisioner per say, but with guest customization itself.

**Comment by jimbodragon** [comment]
Thanks for the answer wduncanfraser, however, it still doesn't work.

As per the guest-os-customization matrix [https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf](https://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf) , custumization of Ubuntu 18.04 LTS works from ESXi 6.5U2 and later.

My team and I will work on the update sooner.

Thanks a lot everyone.
